import json
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    precision_score,
    recall_score,
    roc_auc_score,
)
from xgboost import XGBClassifier

from app.features import MODEL_FEATURES
from ml.generate_data import DATA_PATH, SEED, generate_synthetic_bookings


ARTIFACT_DIR = Path(__file__).resolve().parents[1] / "artifacts"


def _metrics(labels, probabilities, threshold: float = 0.5) -> dict:
    predictions = (probabilities >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(labels, predictions, labels=[0, 1]).ravel()
    return {
        "threshold": threshold,
        "precision": round(float(precision_score(labels, predictions, zero_division=0)), 4),
        "recall": round(float(recall_score(labels, predictions, zero_division=0)), 4),
        "pr_auc": round(float(average_precision_score(labels, probabilities)), 4),
        "roc_auc": round(float(roc_auc_score(labels, probabilities)), 4),
        "false_positive_rate": round(float(fp / max(fp + tn, 1)), 4),
        "confusion_matrix": {"tn": int(tn), "fp": int(fp), "fn": int(fn), "tp": int(tp)},
    }


def _train_model(train: pd.DataFrame, test: pd.DataFrame, label: str) -> tuple[XGBClassifier, dict]:
    model = XGBClassifier(
        n_estimators=220,
        max_depth=4,
        learning_rate=0.045,
        subsample=0.85,
        colsample_bytree=0.85,
        min_child_weight=4,
        reg_lambda=1.5,
        eval_metric="logloss",
        random_state=SEED,
        n_jobs=4,
    )
    model.fit(train[MODEL_FEATURES], train[label])
    probabilities = model.predict_proba(test[MODEL_FEATURES])[:, 1]
    return model, _metrics(test[label], probabilities)


def main() -> None:
    if DATA_PATH.exists():
        frame = pd.read_csv(DATA_PATH)
    else:
        DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
        frame = generate_synthetic_bookings()
        frame.to_csv(DATA_PATH, index=False)

    train_end = frame["event_day"].quantile(0.70)
    validation_end = frame["event_day"].quantile(0.85)
    train = frame[frame["event_day"] <= train_end]
    validation = frame[(frame["event_day"] > train_end) & (frame["event_day"] <= validation_end)]
    test = frame[frame["event_day"] > validation_end]
    train_and_validation = pd.concat([train, validation], ignore_index=True)

    payment_model, payment_metrics = _train_model(
        train_and_validation, test, "payment_fraud_label"
    )
    inventory_model, inventory_metrics = _train_model(
        train_and_validation, test, "inventory_abuse_label"
    )

    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
    payment_model.save_model(ARTIFACT_DIR / "payment_fraud_model.json")
    inventory_model.save_model(ARTIFACT_DIR / "inventory_abuse_model.json")
    metadata = {
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "data_disclosure": "Synthetic data generated by ml.generate_data; metrics are not production evidence.",
        "seed": SEED,
        "row_count": len(frame),
        "split_strategy": "Chronological 70% train, 15% validation, 15% untouched test",
        "split_counts": {
            "train": len(train),
            "validation": len(validation),
            "test": len(test),
        },
        "features": MODEL_FEATURES,
        "test_metrics": {
            "payment_fraud": payment_metrics,
            "inventory_abuse": inventory_metrics,
        },
    }
    (ARTIFACT_DIR / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
